import test from 'node:test';import assert from 'node:assert/strict';
import {dateWindow,mergeUnique,normalizeExternalArticle,plainText,preferenceStore,resolveApiUrl} from '../public/core.js';
test('native API requests always resolve against the HTTPS production API',()=>{assert.equal(resolveApiUrl('/api/football/fixtures',{native:true,config:{API_BASE_URL:'https://api.footballvows.com/'}}),'https://api.footballvows.com/api/football/fixtures');assert.throws(()=>resolveApiUrl('/api/news',{native:true,config:{API_BASE_URL:'http://insecure.test'}}));assert.equal(resolveApiUrl('/api/news',{native:false}),'/api/news')});
test('date navigation makes a seven-day UTC-safe window',()=>assert.deepEqual(dateWindow('2026-08-03'),['2026-07-31','2026-08-01','2026-08-02','2026-08-03','2026-08-04','2026-08-05','2026-08-06']));
test('live events and external stories are deduplicated',()=>{assert.deepEqual(mergeUnique([{id:1},{id:1},{id:2}]).map(x=>x.id),[1,2]);const article=normalizeExternalArticle({title:'<b>Safe</b> &amp; clear',description:'<p>Summary</p>',link:'https://publisher.test/story',pubDate:'2026-08-03'},'Publisher');assert.equal(article.title,'Safe & clear');assert.equal(mergeUnique([article,article]).length,1);assert.equal(normalizeExternalArticle({link:'http://unsafe.test'},'X'),null)});
test('WordPress text is sanitised and preferences persist safely',()=>{assert.equal(plainText('<script>x</script><p>Hello&nbsp;world</p>'),'Hello world');const values=new Map(),storage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)},store=preferenceStore(storage);store.set('teams',[4,7]);assert.deepEqual(store.get('teams',[]),[4,7])});

import {fixtureEndpoint,fixtureError} from '../public/core.js';
import {configuredFootballApiOrigin} from '../public/data.js';
test('fixture requests preserve selected dates and use Worker routes',()=>{assert.equal(fixtureEndpoint('all','2026-08-03'),'/api/fixtures?date=2026-08-03');assert.equal(fixtureEndpoint('live','2026-08-03'),'/api/fixtures/live');assert.throws(()=>fixtureEndpoint('all','2026-02-31x'))});
test('fixture errors distinguish Worker configuration and upstream states',()=>{assert.equal(fixtureError({code:'API_ORIGIN_NOT_CONFIGURED'}).title,'Scores backend is not configured');assert.equal(fixtureError({code:'NOT_CONFIGURED'}).title,'Football provider is not configured');assert.equal(fixtureError({code:'RATE_LIMITED'}).title,'Provider rate limit reached');assert.equal(fixtureError(Error(),{online:false}).title,'Device offline')});
test('Android football origin accepts only deployed HTTPS workers.dev URLs',()=>{assert.equal(configuredFootballApiOrigin('https://footballvows-api.account.workers.dev/',{native:true}),'https://footballvows-api.account.workers.dev');assert.throws(()=>configuredFootballApiOrigin('',{native:true}),e=>e.code==='API_ORIGIN_NOT_CONFIGURED');assert.throws(()=>configuredFootballApiOrigin('https://api-football.com',{native:true}))});
test('Scores and match details use the Worker without removing the calendar',async()=>{const source=await (await import('node:fs/promises')).readFile(new URL('../public/app.js',import.meta.url),'utf8');assert.match(source,/dateWindow\(state\.date,5\)/);assert.match(source,/footballFetch\(fixtureEndpoint\(state\.tab,state\.date\)/);for(const resource of ['events','statistics','lineups','head-to-head','standings','players'])assert.match(source,new RegExp(`'${resource}'`))});
