import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import { dedupeStories, normalizeRss, normalizeWordPressPost, stripHtml } from '../lib/content.mjs';

const wp={id:42,status:'publish',date_gmt:'2026-08-03T12:30:00',link:'https://footballvows.com/story/',title:{rendered:'United &amp; Football'},excerpt:{rendered:'<p>Short <strong>safe</strong> excerpt.</p>'},content:{rendered:'<p>One two three four.</p><script>bad()</script>'},_embedded:{'wp:featuredmedia':[{source_url:'https://footballvows.com/image.jpg'}],author:[{name:'FootballVows Editor'}],'wp:term':[[{taxonomy:'category',name:'Premier League'}]]}};
test('FootballVows WordPress posts retain editorial fields and extract embedded image',()=>{const post=normalizeWordPressPost(wp);assert.equal(post.sourceType,'footballvows');assert.equal(post.image,'https://footballvows.com/image.jpg');assert.equal(post.category,'Premier League');assert.equal(post.author,'FootballVows Editor');assert.equal(post.url,wp.link)});
test('WordPress and RSS HTML is sanitised',()=>{assert.equal(stripHtml('<p>Hello &amp; <b>football</b></p><script>steal()</script>'),'Hello & football');assert.equal(normalizeWordPressPost(wp).summary,'Short safe excerpt.')});
test('external RSS stories keep attribution, short summaries and original links',()=>{const xml=`<rss><channel><item><title><![CDATA[Big football story - BBC Sport]]></title><link>https://bbc.example/story</link><description><![CDATA[<p>A short summary only.</p>]]></description><pubDate>Mon, 03 Aug 2026 12:00:00 GMT</pubDate><source>BBC Sport</source></item></channel></rss>`;const story=normalizeRss(xml,'Football')[0];assert.equal(story.sourceType,'external');assert.equal(story.publisher,'BBC Sport');assert.equal(story.summary,'A short summary only.');assert.equal(story.url,'https://bbc.example/story');assert.equal('content' in story,false)});
test('duplicate external stories are removed',()=>{const story={id:'1',title:'Same Headline',publisher:'Publisher',url:'https://publisher.test/a?tracking=1',publishedAt:'2026-08-03T12:00:00Z'};assert.equal(dedupeStories([story,{...story,id:'2',url:'https://publisher.test/a'}]).length,1)});
test('client keeps News and Blogs separate with fallback, cache, filters and original links',async()=>{const app=await readFile('public/app.js','utf8');assert.match(app,/footballvows\.com\/wp-json\/wp\/v2\/posts/);assert.match(app,/sourceType==='footballvows'/);assert.match(app,/sourceType==='external'/);assert.match(app,/cacheRead\(`news-/);assert.match(app,/data-open/);assert.match(app,/newsFilters/);assert.match(app,/blogFilters/)});
test('profile, onboarding, absolute Android API and protected upload regressions',async()=>{const app=await readFile('public/app.js','utf8'),config=await readFile('public/config.js','utf8');for(const route of ['/profile','/settings','/login','/register','/forgot-password'])assert.ok(app.includes(route));assert.match(app,/footballvows:onboarding-complete/);assert.match(app,/cacheWrite\('onboarding-selections'/);assert.match(app,/profile-button/);assert.match(app,/state\.user\?\.role==='admin'/);assert.match(config,/apiOrigin: ''/)});
test('native API client validates an absolute origin, checks health, times out and retries',async()=>{const data=await readFile('public/data.js','utf8');assert.match(data,/\^https:/);assert.match(data,/\/api\/health/);assert.match(data,/AbortSignal|AbortController/);assert.match(data,/retries=1/);assert.match(data,/API origin:/)});
test('calendar, bottom navigation, onboarding persistence and content controls are actionable',async()=>{const app=await readFile('public/app.js','utf8');for(const route of ["['scores','Scores']","['news','News']","['feed','My Feed']","['blogs','Blogs']","['tv','Vows TV']"])assert.ok(app.includes(route));assert.match(app,/data-date-picker/);assert.match(app,/loadFixtures\(\)/);assert.match(app,/data-onboarding-next/);assert.match(app,/data-bookmark/);assert.match(app,/data-share/);assert.match(app,/data-open/);assert.match(app,/data-refresh-content/)});
test('real FootballVows WordPress endpoint responds when integration network is available',{timeout:12000},async t=>{try{const response=await fetch('https://footballvows.com/wp-json/wp/v2/posts?_embed=1&per_page=10',{signal:AbortSignal.timeout(9000)});if(!response.ok)return t.skip(`endpoint returned ${response.status}`);const posts=await response.json();assert.ok(posts.length>=1);assert.equal(normalizeWordPressPost(posts[0]).sourceType,'footballvows')}catch(error){t.skip(`network unavailable: ${error.message}`)}});
