import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { normalizeEvent, normalizeFixture, normalizeLineup, normalizePlayerStatistics, normalizeStandings } from '../lib/football/contracts.mjs';

const fixture={fixture:{id:77,date:'2026-08-03T18:00:00+00:00',timezone:'UTC',status:{short:'2H',long:'Second Half',elapsed:90,extra:4},venue:{id:2,name:'Stadium',city:'Nairobi'},referee:'A Referee'},league:{id:39,name:'Premier League',country:'England',season:2026,round:'Round 2'},teams:{home:{id:1,name:'Home',logo:'https://img.test/home.png'},away:{id:2,name:'Away',logo:'https://img.test/away.png'}},goals:{home:2,away:1},score:{halftime:{home:1,away:0},fulltime:{home:null,away:null}}};
test('fixture normalization retains timezone, status, elapsed and added time',()=>{const value=normalizeFixture(fixture);assert.equal(value.kickoffUtc,'2026-08-03T18:00:00.000Z');assert.equal(value.status.isLive,true);assert.equal(value.elapsed,90);assert.equal(value.addedTime,4);assert.deepEqual(value.score.halftime,{home:1,away:0})});
test('match events retain scorer, assist and 90+4 timing',()=>{const value=normalizeEvent({id:'g1',time:{elapsed:90,extra:4},team:{id:1,name:'Home'},player:{id:9,name:'Scorer'},assist:{id:10,name:'Creator'},type:'Goal',detail:'Normal Goal'});assert.equal(value.elapsed,90);assert.equal(value.addedTime,4);assert.equal(value.assist.name,'Creator')});
test('lineups retain pitch grid, captain, substitutes and coach',()=>{const value=normalizeLineup({team:{id:1,name:'Home'},formation:'4-3-3',coach:{id:3,name:'Coach'},startXI:[{player:{id:9,name:'Captain',number:9,pos:'F',grid:'4:3',captain:true}}],substitutes:[{player:{id:12,name:'Sub',number:12,pos:'M'}}]});assert.equal(value.formation,'4-3-3');assert.equal(value.starting[0].grid,'4:3');assert.equal(value.starting[0].captain,true);assert.equal(value.substitutes.length,1)});
test('standings and player statistics use stable FootballVows contracts',()=>{const standings=normalizeStandings([{league:{standings:[[{rank:1,team:{id:1,name:'Home'},points:12,goalsDiff:5,form:'WWD',all:{played:5,win:4,draw:0,lose:1,goals:{for:10,against:5}}}]]}}]);assert.deepEqual([standings[0].position,standings[0].wins,standings[0].points],[1,4,12]);const players=normalizePlayerStatistics({team:{id:1,name:'Home'},players:[{player:{id:9,name:'Player'},statistics:[{games:{minutes:90,rating:'7.4'},goals:{total:1,assists:1},passes:{total:42,key:3}}]}]});assert.equal(players.players[0].rating,7.4);assert.equal(players.players[0].keyPasses,3)});
test('Scores requests exact selected date, absolute native backend and status-aware refresh',async()=>{const app=await readFile('public/app.js','utf8'),config=await readFile('public/config.js','utf8');assert.match(config,/https:\/\/app\.footballvows\.com/);assert.match(app,/`\/api\/fixtures\?date=\$\{state\.date\}/);assert.match(app,/Africa\/Nairobi/);assert.match(app,/hasLive\?state\.refreshInterval:300000/);assert.match(app,/fixtures-\$\{state\.tab/)});
test('Scores and all match resources expose honest UI and persistent favourites',async()=>{const app=await readFile('public/app.js','utf8');for(const tab of ['Main','Chat','Prediction','Lineups','Statistics','Standings','Head-to-head','Players','Broadcast'])assert.ok(app.includes(`'${tab}'`));for(const resource of ['events','statistics','lineups','standings','head-to-head','players'])assert.ok(app.includes(resource));assert.match(app,/This information is not available from the current data provider/);assert.match(app,/footballvows:favourites/);assert.match(app,/cacheRead\(`fixtures-/);assert.match(app,/data-refresh-scores/)});
