import { createServer } from 'node:http';
import { readFile, stat } from 'node:fs/promises';
import { extname, join, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ApiFootballProvider, ProviderError } from './lib/football/api-football.mjs';
import { FootballService, validators } from './lib/football/service.mjs';
import { RateLimiter, authenticate, clientKey } from './lib/security.mjs';
import { clearAuthCookies, cookies, createAccount, deleteAccount, exchangeCode, getUser, oauthStart, passwordSignIn, refreshSession, requestPasswordReset, safeNext, sessionCookies, signOut } from './lib/auth.mjs';

const root=fileURLToPath(new URL('./public',import.meta.url)),port=Number(process.env.PORT||3000);
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
const number=(name,fallback,min=1)=>Math.max(min,Number(process.env[name]||fallback));
export const provider=new ApiFootballProvider({baseUrl:process.env.API_FOOTBALL_BASE_URL,key:process.env.API_FOOTBALL_KEY,host:process.env.API_FOOTBALL_HOST,timezone:process.env.API_FOOTBALL_TIMEZONE||'Africa/Nairobi'});
export const football=new FootballService(provider,{liveTtl:number('LIVE_REFRESH_INTERVAL',20)*1000,upcomingTtl:number('UPCOMING_REFRESH_INTERVAL',300)*1000,finishedTtl:number('FINISHED_REFRESH_INTERVAL',86400)*1000,slowTtl:number('FOOTBALL_CACHE_TTL',3600)*1000});
const publicLimit=new RateLimiter({limit:number('PUBLIC_RATE_LIMIT',120)}),adminLimit=new RateLimiter({limit:number('ADMIN_RATE_LIMIT',6)});
const authLimit=new RateLimiter({limit:number('AUTH_RATE_LIMIT',12)});
export const safeDate=validators.date; export const safeId=v=>validators.id(v)?String(v):null;

function send(res,status,body,headers={}){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',...headers});res.end(JSON.stringify(body))}
function error(res,status,code,message,retryable=false){return send(res,status,{error:{code,message,retryable},meta:{provider:provider.name,dataTimestamp:new Date().toISOString(),cache:'none',lastSuccessfulUpdate:provider.metrics.lastSuccess,isLive:false,unavailable:true}})}
const need=(value,name,res)=>value??(error(res,400,'INVALID_PARAMETER',`A valid ${name} is required`),false);

function redirect(res,location,setCookies=[]){res.writeHead(302,{location,'set-cookie':setCookies,'cache-control':'no-store'});res.end()}
async function body(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>16384)throw Object.assign(Error('Request is too large'),{status:413})}try{return JSON.parse(raw||'{}')}catch{throw Object.assign(Error('Invalid JSON request'),{status:400})}}
function allowedOrigin(origin){if(!origin)return false;let production;try{production=new URL(process.env.PUBLIC_APP_URL).origin}catch{return false}return new Set([production,'https://localhost','capacitor://localhost']).has(origin)}
function sameOrigin(req){if(!['POST','DELETE'].includes(req.method))return true;const origin=req.headers.origin;if(!origin)return process.env.NODE_ENV==='test';return allowedOrigin(origin)}
function cors(req,res){const origin=req.headers.origin;if(allowedOrigin(origin)){res.setHeader('access-control-allow-origin',origin);res.setHeader('access-control-allow-credentials','true');res.setHeader('vary','Origin');res.setHeader('access-control-allow-methods','GET, POST, DELETE, OPTIONS');res.setHeader('access-control-allow-headers','Content-Type, Authorization')}}
async function authApi(req,res,url){
  const limited=authLimit.check(clientKey(req));if(!limited.allowed)return error(res,429,'AUTH_RATE_LIMIT','Too many sign-in attempts. Please wait and try again.',true);
  try{
    if(url.pathname==='/api/auth/google'){const start=oauthStart(safeNext(url.searchParams.get('next')),url.searchParams.get('platform')==='android'?'android':'web');return redirect(res,start.url,start.cookies)}
    if(url.pathname==='/api/auth/callback'){const saved=cookies(req),code=url.searchParams.get('code'),state=url.searchParams.get('state'),providerError=url.searchParams.get('error');if(providerError)return redirect(res,'/login?auth_error=cancelled',clearAuthCookies());if(!code||!state||state!==saved.fv_oauth_state||!saved.fv_pkce)return redirect(res,'/login?auth_error=invalid_callback',clearAuthCookies());const session=await exchangeCode(code,saved.fv_pkce),next=safeNext(saved.fv_auth_next),destination=saved.fv_auth_platform==='android'?`com.footballvows.app://auth/complete?next=${encodeURIComponent(next)}`:next;return redirect(res,destination,[...sessionCookies(session),...clearAuthCookies().slice(2)])}
    if(url.pathname==='/api/auth/session'&&req.method==='GET'){let jar=cookies(req),user;try{user=await getUser(jar.fv_access)}catch{if(!jar.fv_refresh)return send(res,401,{error:{code:'SESSION_EXPIRED',message:'Your FootballVows session has expired.'}});const refreshed=await refreshSession(jar.fv_refresh);res.setHeader('set-cookie',sessionCookies(refreshed));user=refreshed.user||await getUser(refreshed.access_token)}return send(res,200,{data:{user:{id:user.id,email:user.email,displayName:user.user_metadata?.display_name||user.user_metadata?.full_name||'FootballVows supporter',avatarUrl:user.user_metadata?.avatar_url||null}},meta:{authenticated:true}})}
    if(!sameOrigin(req))return error(res,403,'INVALID_ORIGIN','The authentication request origin is not allowed.');
    if(url.pathname==='/api/auth/email'&&req.method==='POST'){const input=await body(req);if(!/^\S+@\S+\.\S+$/.test(input.email||'')||String(input.password||'').length<8)return error(res,400,'INVALID_CREDENTIALS','Enter a valid email and a password of at least 8 characters.');const session=await passwordSignIn(input.email,input.password);res.setHeader('set-cookie',sessionCookies(session));return send(res,200,{data:{next:safeNext(input.next)}})}
    if(url.pathname==='/api/auth/register'&&req.method==='POST'){const input=await body(req);if(!/^\S+@\S+\.\S+$/.test(input.email||'')||String(input.password||'').length<8)return error(res,400,'INVALID_REGISTRATION','Enter a valid email and a password of at least 8 characters.');const result=await createAccount(input.email,input.password,String(input.displayName||'').slice(0,80));if(result.access_token)res.setHeader('set-cookie',sessionCookies(result));return send(res,201,{data:{emailConfirmationRequired:!result.access_token,next:safeNext(input.next)}})}
    if(url.pathname==='/api/auth/forgot-password'&&req.method==='POST'){const input=await body(req);if(!/^\S+@\S+\.\S+$/.test(input.email||''))return error(res,400,'INVALID_EMAIL','Enter a valid email address.');await requestPasswordReset(input.email);return send(res,200,{data:{sent:true}})}
    if(url.pathname==='/api/auth/signout'&&req.method==='POST'){const jar=cookies(req);await signOut(jar.fv_access);res.setHeader('set-cookie',clearAuthCookies());return send(res,200,{data:{signedOut:true}})}
    if(url.pathname==='/api/auth/account'&&req.method==='DELETE'){const auth=await authenticate(req);if(!auth.authenticated)return error(res,401,'SESSION_EXPIRED','Sign in again before deleting your account.');await deleteAccount(auth.user.id);res.setHeader('set-cookie',clearAuthCookies());return send(res,200,{data:{deleted:true}})}
    return error(res,404,'NOT_FOUND','Authentication endpoint not found');
  }catch(e){const code=e.code||'AUTH_NETWORK_ERROR',status=e.status||503;if(url.pathname==='/api/auth/callback')return redirect(res,`/login?auth_error=${encodeURIComponent(code.toLowerCase())}`,clearAuthCookies());return error(res,status,code,e.message||'FootballVows sign-in is temporarily unavailable',status>=500)}
}

async function footballApi(req,res,url){
  const rate=publicLimit.check(clientKey(req));res.setHeader('x-ratelimit-remaining',rate.remaining);if(!rate.allowed)return error(res,429,'CLIENT_RATE_LIMIT','Too many requests. Please try again shortly.',true);
  const auth=await authenticate(req);res.setHeader('x-footballvows-auth',auth.authenticated?'authenticated':'guest');
  const p=url.pathname,force=url.searchParams.get('refresh')==='true';
  try{
    if(p==='/api/football/status')return send(res,200,football.status());
    if(p==='/api/football/fixtures/live')return send(res,200,await football.live(force));
    if(p==='/api/football/fixtures'){const date=need(validators.date(url.searchParams.get('date')),'date',res);if(!date)return;return send(res,200,await football.fixtures(date,force))}
    let m;
    if((m=p.match(/^\/api\/football\/fixtures\/(\d+)$/))){const id=need(validators.id(m[1]),'fixture ID',res);if(!id)return;return send(res,200,await football.fixture(id))}
    if((m=p.match(/^\/api\/football\/fixtures\/(\d+)\/(events|statistics|lineups|players|head-to-head)$/))){const id=need(validators.id(m[1]),'fixture ID',res);if(!id)return;const kind=m[2];if(kind==='events')return send(res,200,await football.events(id));if(kind==='statistics')return send(res,200,await football.statistics(id));if(kind==='lineups')return send(res,200,await football.lineups(id));if(kind==='players')return send(res,200,await football.players(id));const fixture=(await football.fixture(id)).data;if(!fixture)return error(res,404,'NOT_FOUND','Fixture not found');return send(res,200,await football.headToHead(fixture.home.id,fixture.away.id))}
    if(p==='/api/football/leagues'){const season=url.searchParams.get('season');if(season&&!validators.season(season))return error(res,400,'INVALID_PARAMETER','A valid season is required');return send(res,200,await football.leagues(season?{season}:{}))}
    if((m=p.match(/^\/api\/football\/leagues\/(\d+)\/standings$/))){const league=need(validators.id(m[1]),'league ID',res),season=need(validators.season(url.searchParams.get('season')),'season',res);if(!league||!season)return;return send(res,200,await football.standings(league,season))}
    if((m=p.match(/^\/api\/football\/teams\/(\d+)$/))){const id=need(validators.id(m[1]),'team ID',res);if(!id)return;return send(res,200,await football.team(id))}
    if((m=p.match(/^\/api\/football\/teams\/(\d+)\/(fixtures|squad)$/))){const id=need(validators.id(m[1]),'team ID',res);if(!id)return;if(m[2]==='squad')return send(res,200,await football.squad(id));const season=need(validators.season(url.searchParams.get('season')),'season',res);if(!season)return;return send(res,200,await football.teamFixtures(id,season))}
    if((m=p.match(/^\/api\/football\/players\/(\d+)$/))){const id=need(validators.id(m[1]),'player ID',res),season=need(validators.season(url.searchParams.get('season')),'season',res);if(!id||!season)return;return send(res,200,await football.player(id,season))}
    if(p==='/api/football/search'){const q=need(validators.query(url.searchParams.get('q')),'search query',res);if(!q)return;return send(res,200,await football.search(q))}
    if(p==='/api/football/admin/refresh'){if(req.method!=='POST')return error(res,405,'METHOD_NOT_ALLOWED','Use POST for manual refresh');if(!auth.authenticated||auth.role!=='admin')return error(res,403,'FORBIDDEN','Administrator access required');const ar=adminLimit.check(`admin:${auth.user.id}`);if(!ar.allowed)return error(res,429,'ADMIN_RATE_LIMIT','Manual refresh limit reached',true);football.cache.clear('fixtures:');return send(res,200,{data:{cleared:true},meta:{provider:provider.name,dataTimestamp:new Date().toISOString(),cache:'cleared',lastSuccessfulUpdate:provider.metrics.lastSuccess,isLive:false,unavailable:false}})}
    return error(res,404,'NOT_FOUND','Football endpoint not found');
  }catch(e){const status=e instanceof ProviderError?e.status:503;return error(res,status,e.code||'TEMPORARY_FAILURE',e.message||'Football data is temporarily unavailable',e.retryable!==false)}
}

async function newsApi(res,url){try{const endpoint=process.env.WORDPRESS_API_URL||'https://www.footballvows.com/wp-json/wp/v2',page=Math.max(1,Math.min(100,Number(url.searchParams.get('page')||1)));const r=await fetch(`${endpoint}/posts?_embed=1&per_page=12&page=${page}`,{signal:AbortSignal.timeout(9000)});if(!r.ok)throw Error(`News provider returned ${r.status}`);return send(res,200,{data:await r.json(),meta:{provider:'footballvows_wordpress',dataTimestamp:new Date().toISOString(),cache:'miss',unavailable:false}})}catch(e){return error(res,503,'NEWS_UNAVAILABLE',e.message,true)}}
async function serve(res,url){const requested=url.pathname==='/'?'index.html':url.pathname.slice(1),clean=normalize(requested).replace(/^(\.\.[/\\])+/, '');let file=join(root,clean);try{if(!(await stat(file)).isFile())throw Error()}catch{file=join(root,'index.html')}const body=await readFile(file);res.writeHead(200,{'content-type':types[extname(file)]||'application/octet-stream','cache-control':extname(file)==='.html'?'no-cache':'public, max-age=3600','x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin','permissions-policy':'camera=(), microphone=(), geolocation=()','content-security-policy':"default-src 'self'; img-src 'self' https: data:; connect-src 'self' https://app.footballvows.com https://*.supabase.co; style-src 'self'; script-src 'self'; frame-src https://www.youtube-nocookie.com; object-src 'none'; base-uri 'self'; frame-ancestors 'none'"});res.end(body)}

export const server=createServer(async(req,res)=>{cors(req,res);if(req.method==='OPTIONS'){res.writeHead(204);return res.end()}const url=new URL(req.url,'http://footballvows.internal');if(url.pathname==='/api/health')return send(res,200,{ok:true,footballConfigured:Boolean(provider.key),authenticationConfigured:Boolean(process.env.SUPABASE_URL),timestamp:new Date().toISOString()});if(url.pathname==='/api/config')return send(res,200,{footballBackend:'/api/football',defaultTimezone:provider.timezone,liveRefreshInterval:football.ttl.live,authenticationConfigured:Boolean(process.env.SUPABASE_URL)});if(url.pathname.startsWith('/api/auth/'))return authApi(req,res,url);if(url.pathname.startsWith('/api/football/'))return footballApi(req,res,url);if(url.pathname==='/api/news')return newsApi(res,url);try{return await serve(res,url)}catch{return error(res,500,'APP_ERROR','Unable to load FootballVows')}});
if(process.env.NODE_ENV!=='test')server.listen(port,()=>console.log(`FootballVows is ready on port ${port}`));
