-- Additive FootballVows foundation. Back up and test against staging before production.
create extension if not exists pgcrypto;
create type public.app_role as enum ('user','writer','moderator','admin');
create type public.content_status as enum ('draft','published','archived');

create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, username text unique, display_name text, avatar_url text, preferences jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.user_roles (user_id uuid references auth.users(id) on delete cascade, role public.app_role not null default 'user', created_at timestamptz not null default now(), primary key(user_id,role));
create table if not exists public.favourite_teams (user_id uuid references auth.users(id) on delete cascade, team_id bigint not null, team_name text, created_at timestamptz not null default now(), primary key(user_id,team_id));
create table if not exists public.favourite_players (user_id uuid references auth.users(id) on delete cascade, player_id bigint not null, player_name text, created_at timestamptz not null default now(), primary key(user_id,player_id));
create table if not exists public.favourite_matches (user_id uuid references auth.users(id) on delete cascade, fixture_id bigint not null, created_at timestamptz not null default now(), primary key(user_id,fixture_id));
create table if not exists public.followed_competitions (user_id uuid references auth.users(id) on delete cascade, competition_id bigint not null, created_at timestamptz not null default now(), primary key(user_id,competition_id));
create table if not exists public.pinned_matches (user_id uuid references auth.users(id) on delete cascade, fixture_id bigint not null, created_at timestamptz not null default now(), primary key(user_id,fixture_id));
create table if not exists public.bookmarked_articles (user_id uuid references auth.users(id) on delete cascade, article_id bigint not null, created_at timestamptz not null default now(), primary key(user_id,article_id));
create table if not exists public.followed_articles (user_id uuid references auth.users(id) on delete cascade, article_id bigint not null, created_at timestamptz not null default now(), primary key(user_id,article_id));
create table if not exists public.notification_preferences (user_id uuid primary key references auth.users(id) on delete cascade, preferences jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now());
create table if not exists public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, kind text not null, title text not null, body text, data jsonb not null default '{}'::jsonb, read_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.match_votes (user_id uuid references auth.users(id) on delete cascade, fixture_id bigint not null, selection text not null check(selection in ('home','draw','away')), created_at timestamptz not null default now(), primary key(user_id,fixture_id));
create table if not exists public.match_comments (id uuid primary key default gen_random_uuid(), fixture_id bigint not null, user_id uuid references auth.users(id) on delete cascade, parent_id uuid references public.match_comments(id) on delete cascade, body text not null check(char_length(body) between 1 and 1500), removed_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.comment_reports (id uuid primary key default gen_random_uuid(), comment_id uuid references public.match_comments(id) on delete cascade, reporter_id uuid references auth.users(id) on delete cascade, reason text not null, resolved_at timestamptz, created_at timestamptz not null default now(), unique(comment_id,reporter_id));
create table if not exists public.user_posts (id uuid primary key default gen_random_uuid(), author_id uuid references auth.users(id) on delete cascade, title text not null, body text not null, status public.content_status not null default 'draft', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.discussion_threads (id uuid primary key default gen_random_uuid(), author_id uuid references auth.users(id) on delete cascade, title text not null, body text not null, locked_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.video_categories (id uuid primary key default gen_random_uuid(), name text unique not null);
create table if not exists public.videos (id uuid primary key default gen_random_uuid(), creator_id uuid references auth.users(id), category_id uuid references public.video_categories(id), title text not null, description text, thumbnail_url text, video_url text not null, status public.content_status not null default 'draft', featured boolean not null default false, view_count bigint not null default 0, published_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.premium_subscriptions (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, provider text not null, provider_reference text unique, status text not null, expires_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.prediction_requests (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id), fixture_id bigint not null, status text not null default 'pending', created_at timestamptz not null default now());
create table if not exists public.prediction_results (id uuid primary key default gen_random_uuid(), request_id uuid unique references public.prediction_requests(id) on delete cascade, likely_score text, confidence numeric check(confidence between 0 and 1), data_quality text, supporting_factors jsonb, risks jsonb, sources jsonb, model_version text, created_at timestamptz not null default now());
create table if not exists public.prediction_markets (id uuid primary key default gen_random_uuid(), result_id uuid references public.prediction_results(id) on delete cascade, market text not null, selection text not null, probability numeric not null check(probability between 0 and 1), usefulness numeric check(usefulness between 0 and 1), is_featured boolean not null default false);
create table if not exists public.app_settings (key text primary key, value jsonb not null, updated_at timestamptz not null default now());
create table if not exists public.featured_competitions (competition_id bigint primary key, sort_order integer not null default 0, created_at timestamptz not null default now());
create table if not exists public.promoted_matches (fixture_id bigint primary key, starts_at timestamptz, ends_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.announcements (id uuid primary key default gen_random_uuid(), title text not null, body text not null, status public.content_status not null default 'draft', published_at timestamptz);
create table if not exists public.advertising_slots (key text primary key, placement text not null, enabled boolean not null default false, configuration jsonb not null default '{}'::jsonb);
create table if not exists public.audit_logs (id bigint generated always as identity primary key, actor_id uuid references auth.users(id), action text not null, entity_type text, entity_id text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());

create index if not exists notifications_user_created_idx on public.notifications(user_id,created_at desc);
create index if not exists comments_fixture_created_idx on public.match_comments(fixture_id,created_at);
create index if not exists predictions_user_created_idx on public.prediction_requests(user_id,created_at desc);

create or replace function public.has_role(required_role public.app_role) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.user_roles where user_id=auth.uid() and role=required_role) $$;
alter table public.profiles enable row level security; alter table public.user_roles enable row level security;
do $$ declare t text; begin foreach t in array array['favourite_teams','favourite_players','favourite_matches','followed_competitions','pinned_matches','bookmarked_articles','followed_articles','notification_preferences','notifications','match_votes','match_comments','comment_reports','user_posts','discussion_threads','premium_subscriptions','prediction_requests','videos'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
create policy "profiles readable" on public.profiles for select using (true);
create policy "profiles owned" on public.profiles for all using (auth.uid()=id) with check(auth.uid()=id);
create policy "roles self readable" on public.user_roles for select using (auth.uid()=user_id or public.has_role('admin'));
do $$ declare t text; begin foreach t in array array['favourite_teams','favourite_players','favourite_matches','followed_competitions','pinned_matches','bookmarked_articles','followed_articles','notification_preferences','notifications','match_votes','match_comments','premium_subscriptions','prediction_requests'] loop execute format('create policy "owned rows" on public.%I for all using (auth.uid()=user_id) with check (auth.uid()=user_id)',t); end loop; end $$;
create policy "owned reports" on public.comment_reports for all using(auth.uid()=reporter_id) with check(auth.uid()=reporter_id);
create policy "owned posts" on public.user_posts for all using(auth.uid()=author_id) with check(auth.uid()=author_id);
create policy "owned threads" on public.discussion_threads for all using(auth.uid()=author_id) with check(auth.uid()=author_id);
create policy "published videos readable" on public.videos for select using(status='published');
